### ISSUE TITLE
Error: Could not obtain a key container: Unknown PKI error 0x8009001A

### ISSUE THREAD

**Issue by ratsrolocosx** [pbatard/libwdi#168] opened 2019-10-10 01:29 UTC
I am trying to download driver's onto my gamecube adapter, it's listed as WUP-028, and the driver installation fails everytime. I have tried running as admin, and restarting my computer. 

```
Zadig 2.4.721
Windows 10 64-bit (Build 17763)
ini file 'zadig.ini' not found - default parameters will be used
default driver set to 'WinUSB'
0 devices found.
14 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_5253&PID_0002&MI_00\7&3893EB83&0&0000
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (6): USB\VID_1038&PID_1369&MI_03\7&22ACC5E&0&0003
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_046D&PID_0825&REV_0012&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_01&SubClass_02&Prot_00
libwdi:debug [wdi_create_list] Upper filter: lvrs64
libwdi:debug [wdi_create_list] Driver version: 13.80.853.0
libwdi:debug [wdi_create_list] usbaudio USB device (7): USB\VID_046D&PID_0825&MI_02\6&1A4C3D6B&0&0002
libwdi:debug [wdi_create_list] Device description: 'HD Webcam C270 (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (8): USB\VID_5253&PID_0002&MI_01\7&3893EB83&0&0001
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (9): USB\VID_1038&PID_1369&MI_02\7&22ACC5E&0&0002
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 2.4.10.1
libwdi:debug [wdi_create_list] mshidkmdf USB device (10): USB\VID_1038&PID_1369&MI_01\7&22ACC5E&0&0001
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (11): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (12): USB\VID_1038&PID_1369&MI_00\7&22ACC5E&0&0000
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (13): USB\VID_5253&PID_0002&MI_02\7&3893EB83&0&0002
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1397&PID_0507&REV_0112
libwdi:debug [wdi_create_list] Compatible ID: USB\DevClass_00&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 4.59.0.56775
libwdi:debug [wdi_create_list] umc_audio USB device (14): USB\VID_1397&PID_0507\5&212AC8FC&0&3
libwdi:debug [wdi_create_list] Device description: 'UMC202HD 192k'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (15): USB\VID_5253&PID_0002&MI_03\7&3893EB83&0&0003
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_8087&PID_07DC&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_E0&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 20.60.0.4
libwdi:debug [wdi_create_list] BTHUSB USB device (17): USB\VID_8087&PID_07DC\5&212AC8FC&0&11
libwdi:debug [wdi_create_list] Device description: 'Intel(R) Wireless Bluetooth(R)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_046D&PID_0825&REV_0012&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 13.80.853.0
libwdi:debug [wdi_create_list] LVUVC64 USB device (19): USB\VID_046D&PID_0825&MI_00\6&1A4C3D6B&0&0000
libwdi:debug [wdi_create_list] Device description: 'Logitech HD Webcam C270 (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_04
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (20): USB\VID_5253&PID_0002&MI_04\7&3893EB83&0&0004
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 4)'
Using inf name: WUP-028.inf
Successfully extracted driver files.
libwdi:info [extract_binaries] successfully extracted driver files to C:\Users\adame\usb_driver
libwdi:info [wdi_prepare_driver] successfully created 'C:\Users\adame\usb_driver\WUP-028.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\adame\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\adame\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'wup-028.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\adame\usb_driver\wup-028.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\adame\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\adame\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] successfully created file 'C:\Users\adame\usb_driver\WUP-028.cat'
libwdi:debug [CreateSelfSignedCert] set Enhanced Key Usage, URL and CPS
libwdi:warning [CreateSelfSignedCert] could not obtain a key container: Unknown PKI error 0x8009001A
libwdi:warning [wdi_prepare_driver] could not sign cat file
Installing driver. Please wait...
libwdi:debug [wdi_install_driver] using progress bar mode
libwdi:debug [installer process] got parameter WUP-028.inf
libwdi:debug [process_message] got request for device_id
libwdi:debug [installer process] got device_id: 'USB\VID_057E&PID_0337\15/07/2014'
libwdi:debug [process_message] got request for hardware_id
libwdi:debug [installer process] got hardware_id: 'USB\VID_057E&PID_0337&REV_0100'
libwdi:debug [installer process] got user_sid: 'S-1-5-21-1141364396-1352916837-1890854036-1001'
libwdi:debug [installer process] using syslog 'C:\WINDOWS\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] switching timeout to infinite
libwdi:debug [installer process] Installing driver for USB\VID_057E&PID_0337&REV_0100 - please wait...
libwdi:debug [syslog] <Garbled data>
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2019/10/09 18:27:58.056
libwdi:debug [syslog]       cmd: "C:\Users\adame\usb_driver\installer_x64.exe" "WUP-028.inf"
libwdi:debug [syslog]      ndv: INF path: C:\Users\adame\usb_driver\WUP-028.inf
libwdi:debug [syslog]      ndv: Install flags: 0x00000001
libwdi:debug [syslog]      ndv: {Update Device Driver - USB\VID_057E&PID_0337\15/07/2014}
libwdi:debug [syslog]      ndv:      Search options: 0x00000080
libwdi:debug [syslog]      ndv:      Searching single INF 'C:\Users\adame\usb_driver\WUP-028.inf'
libwdi:debug [syslog]      dvi:      {Build Driver List} 18:27:58.097
libwdi:debug [syslog]      dvi:           Searching for hardware ID(s):
libwdi:debug [syslog]      dvi:                usb\vid_057e&pid_0337&rev_0100
libwdi:debug [syslog]      dvi:                usb\vid_057e&pid_0337
libwdi:debug [syslog]      dvi:           Searching for compatible ID(s):
libwdi:debug [syslog]      dvi:                usb\class_03&subclass_00&prot_00
libwdi:debug [syslog]      dvi:                usb\class_03&subclass_00
libwdi:debug [syslog]      dvi:                usb\class_03
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE} 18:27:58.148
libwdi:debug [syslog]      sig:                Key      = wup-028.inf
libwdi:debug [syslog]      sig:                FilePath = c:\users\adame\usb_driver\wup-028.inf
libwdi:debug [syslog]      sig:                Catalog  = c:\users\adame\usb_driver\WUP-028.cat
libwdi:debug [syslog] !    sig:                Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                Error 0x800b0100: No signature was present in the subject.
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE exit(0x800b0100)} 18:27:58.193
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE} 18:27:58.197
libwdi:debug [syslog]      sig:                Key      = wup-028.inf
libwdi:debug [syslog]      sig:                FilePath = c:\users\adame\usb_driver\wup-028.inf
libwdi:debug [syslog]      sig:                Catalog  = c:\users\adame\usb_driver\WUP-028.cat
libwdi:debug [syslog] !    sig:                Verifying file against specific Authenticode(tm) catalog failed.
libwdi:debug [syslog] !    sig:                Error 0x800b0100: No signature was present in the subject.
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE exit(0x800b0100)} 18:27:58.222
libwdi:debug [syslog]      dvi:           Created Driver Node:
libwdi:debug [syslog]      dvi:                HardwareID   - USB\VID_057E&PID_0337
libwdi:debug [syslog]      dvi:                InfName      - c:\users\adame\usb_driver\wup-028.inf
libwdi:debug [syslog]      dvi:                DevDesc      - WUP-028
libwdi:debug [syslog]      dvi:                Section      - USB_Install
libwdi:debug [syslog]      dvi:                Rank         - 0x80ff0001
libwdi:debug [syslog]      dvi:                Signer Score - Not digitally signed
libwdi:debug [syslog]      dvi:                DrvDate      - 02/10/2017
libwdi:debug [syslog]      dvi:                Version      - 6.1.7600.16385
libwdi:debug [syslog]      dvi:      {Build Driver List - exit(0x00000000)} 18:27:58.264
libwdi:debug [syslog]      dvi:      {DIF_SELECTBESTCOMPATDRV} 18:27:58.268
libwdi:debug [syslog]      dvi:           Default installer: Enter 18:27:58.272
libwdi:debug [syslog]      dvi:                {Select Best Driver}
libwdi:debug [syslog]      dvi:                     Class GUID of device changed to: {88bae032-5a81-49f0-bc3d-a4ff138216d6}.
libwdi:debug [syslog]      dvi:                     Selected Driver:
libwdi:debug [syslog]      dvi:                          Description - WUP-028
libwdi:debug [syslog]      dvi:                          InfFile     - c:\users\adame\usb_driver\wup-028.inf
libwdi:debug [syslog]      dvi:                          Section     - USB_Install
libwdi:debug [syslog]      dvi:                {Select Best Driver - exit(0x00000000)}
libwdi:debug [syslog]      dvi:           Default installer: Exit
libwdi:debug [syslog]      dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0x00000000)} 18:27:58.307
libwdi:debug [syslog]      ndv:      Force Installing Driver:
libwdi:debug [syslog]      ndv:           Inf Name       - wup-028.inf
libwdi:debug [syslog]      ndv:           Driver Date    - 02/10/2017
libwdi:debug [syslog]      ndv:           Driver Version - 6.1.7600.16385
libwdi:debug [syslog]      sto:      {Setup Import Driver Package: c:\users\adame\usb_driver\wup-028.inf} 18:27:58.328
libwdi:debug [syslog]      inf:           Provider: libwdi
libwdi:debug [syslog]      inf:           Class GUID: {88bae032-5a81-49f0-bc3d-a4ff138216d6}
libwdi:debug [syslog]      inf:           Driver Version: 02/10/2017,6.1.7600.16385
libwdi:debug [syslog]      inf:           Catalog File: WUP-028.cat
libwdi:debug [syslog]      sto:           {Copy Driver Package: c:\users\adame\usb_driver\wup-028.inf} 18:27:58.351
libwdi:debug [syslog]      sto:                Driver Package = c:\users\adame\usb_driver\wup-028.inf
libwdi:debug [syslog]      sto:                Flags          = 0x00000007
libwdi:debug [syslog]      sto:                Destination    = C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}
libwdi:debug [syslog]      sto:                Copying driver package files to 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\adame\usb_driver\amd64\WdfCoInstaller01011.dll' to 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\adame\usb_driver\amd64\WinUSBCoInstaller2.dll' to 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\adame\usb_driver\WUP-028.cat' to 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\adame\usb_driver\wup-028.inf' to 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\wup-028.inf'.
libwdi:debug [syslog]      sto:           {Copy Driver Package: exit(0x00000000)} 18:27:58.404
libwdi:debug [syslog]      pol:           {Driver package policy check} 18:27:58.451
libwdi:debug [syslog]      pol:           {Driver package policy check - exit(0x00000000)} 18:27:58.452
libwdi:debug [syslog]      sto:           {Stage Driver Package: C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\wup-028.inf} 18:27:58.452
libwdi:debug [syslog]      inf:                {Query Configurability: C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\wup-028.inf} 18:27:58.456
libwdi:debug [syslog]      inf:                     Driver package uses WDF.
libwdi:debug [syslog]      inf:                     Driver package 'wup-028.inf' is configurable.
libwdi:debug [syslog]      inf:                {Query Configurability: exit(0x00000000)} 18:27:58.459
libwdi:debug [syslog]      flq:                Copying 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\amd64\WdfCoInstaller01011.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\amd64\WinUSBCoInstaller2.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\WUP-028.cat' to 'C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\adame\AppData\Local\Temp\{ba7bc33e-6a2b-ed4f-ad83-03503d475264}\wup-028.inf' to 'C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\wup-028.inf'.
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE} 18:27:58.498
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 18:27:58.512
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\WUP-028.cat
libwdi:debug [syslog] !    sig:                          Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                          Error 0x800b0100: No signature was present in the subject.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0x800b0100)} 18:27:58.517
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 18:27:58.518
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{8ce5176b-b4e0-604a-a899-1e7c1fc2d600}\WUP-028.cat
libwdi:debug [syslog] !    sig:                          Verifying file against specific Authenticode(tm) catalog failed.
libwdi:debug [syslog] !    sig:                          Error 0x800b0100: No signature was present in the subject.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0x800b0100)} 18:27:58.521
libwdi:debug [syslog] !!!  sig:                     Driver package catalog file does not contain a signature, and Code Integrity is enforced.
libwdi:debug [syslog] !!!  sig:                     Driver package failed signature validation. Error = 0xE0000247
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE: exit(0xe0000247)} 18:27:58.523
libwdi:debug [syslog] !!!  sig:                Driver package failed signature verification. Error = 0xE0000247
libwdi:debug [syslog] !!!  sto:                Failed to import driver package into Driver Store. Error = 0xE0000247
libwdi:debug [syslog]      sto:           {Stage Driver Package: exit(0xe0000247)} 18:27:58.525
libwdi:debug [syslog]      sto:      {Setup Import Driver Package - exit (0xe0000247)} 18:27:58.533
libwdi:debug [process_message] switching timeout back to finite
libwdi:debug [installer process] operation cancelled by the user
libwdi:debug [process_message] installer process completed
Driver Installation: Cancelled by User
14 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_5253&PID_0002&MI_00\7&3893EB83&0&0000
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (6): USB\VID_1038&PID_1369&MI_03\7&22ACC5E&0&0003
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_046D&PID_0825&REV_0012&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_01&SubClass_02&Prot_00
libwdi:debug [wdi_create_list] Upper filter: lvrs64
libwdi:debug [wdi_create_list] Driver version: 13.80.853.0
libwdi:debug [wdi_create_list] usbaudio USB device (7): USB\VID_046D&PID_0825&MI_02\6&1A4C3D6B&0&0002
libwdi:debug [wdi_create_list] Device description: 'HD Webcam C270 (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (8): USB\VID_5253&PID_0002&MI_01\7&3893EB83&0&0001
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (9): USB\VID_1038&PID_1369&MI_02\7&22ACC5E&0&0002
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 2.4.10.1
libwdi:debug [wdi_create_list] mshidkmdf USB device (10): USB\VID_1038&PID_1369&MI_01\7&22ACC5E&0&0001
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (11): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1038&PID_1369&REV_0114&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (12): USB\VID_1038&PID_1369&MI_00\7&22ACC5E&0&0000
libwdi:debug [wdi_create_list] Device description: 'Sensei Raw Gaming Mouse (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (13): USB\VID_5253&PID_0002&MI_02\7&3893EB83&0&0002
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1397&PID_0507&REV_0112
libwdi:debug [wdi_create_list] Compatible ID: USB\DevClass_00&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 4.59.0.56775
libwdi:debug [wdi_create_list] umc_audio USB device (14): USB\VID_1397&PID_0507\5&212AC8FC&0&3
libwdi:debug [wdi_create_list] Device description: 'UMC202HD 192k'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (15): USB\VID_5253&PID_0002&MI_03\7&3893EB83&0&0003
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_8087&PID_07DC&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_E0&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 20.60.0.4
libwdi:debug [wdi_create_list] BTHUSB USB device (17): USB\VID_8087&PID_07DC\5&212AC8FC&0&11
libwdi:debug [wdi_create_list] Device description: 'Intel(R) Wireless Bluetooth(R)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_046D&PID_0825&REV_0012&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 13.80.853.0
libwdi:debug [wdi_create_list] LVUVC64 USB device (19): USB\VID_046D&PID_0825&MI_00\6&1A4C3D6B&0&0000
libwdi:debug [wdi_create_list] Device description: 'Logitech HD Webcam C270 (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_5253&PID_0002&REV_0002&MI_04
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.17763.719
libwdi:debug [wdi_create_list] HidUsb USB device (20): USB\VID_5253&PID_0002&MI_04\7&3893EB83&0&0004
libwdi:debug [wdi_create_list] Device description: 'Red Scarf II+ (Interface 4)'
Checking for Zadig updates...

Checking release channel...
```

**Comment by pbatard** [comment] 2019-10-10 08:45
The problem is that, on your machine, Zadig/libwdi can not sign the `.cat` file:
```
libwdi:warning [CreateSelfSignedCert] could not obtain a key container: Unknown PKI error 0x8009001A
libwdi:warning [wdi_prepare_driver] could not sign cat file
```
As a result, since driver signature is enforced, the driver installation fails:
```
libwdi:debug [syslog] !!!  sig:                     Driver package catalog file does not contain a signature, and Code Integrity is enforced.
libwdi:debug [syslog] !!!  sig:                     Driver package failed signature validation. Error = 0xE0000247
```

Error `0x8009001A` is `NTE_KEYSET_ENTRY_BAD` which seems to indicate that a storage cryptographic container from your system is corrupt.

In other words, something must have been altered on your system, compared to a vanilla Windows 10 installation, that makes the call to [`CryptAcquireContext()`](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-cryptacquirecontextw) fail with this error, and it is not something that Zadig/libwdi can fix.

According to [this](https://social.msdn.microsoft.com/Forums/en-US/f3ae9010-d5c0-4fd2-a863-b4527a605050/error-8009001a?forum=theforumofsho) you may have to the file from in `C:\Users\<userID>\AppData\Roaming\Microsoft\Crypto\RSA\` that got corrupted, but I'm afraid I can't help you identify which one.

At any rate, I'm afraid this issue is environmental, and it appears that you have corruption issues with your cryptography containers.

**Comment by pbatard** [comment] 2019-10-18 23:42
No update from OP &rarr; Closing

**Closed by pbatard** 2019-10-18 23:42 UTC
