### ISSUE TITLE
Windows 11 Driver Installation Failed (Operation not supported or not implemented)

### ISSUE THREAD

**Issue by PhantomTrainer2** [pbatard/libwdi#244] opened 2021-12-26 16:17 UTC
I have recently updated my computer to windows 11 and my Gamecube controller stopped working, so I tryied reinstalling the drivers with zadig 2.7 but it always gives me the same error: "(Operation not supported or not implemented)". Is there a solution?

**Comment by pbatard** [comment] 2021-12-26 16:38
You'll need to provide the full log from Zadig.

**Comment by PhantomTrainer2** [comment] 2021-12-26 17:49
> You'll need to provide the full log from Zadig.

Using inf name: WUP-028.inf
Successfully extracted driver files.
libwdi:info [extract_binaries] Successfully extracted driver files to 'C:\Users\Breno\usb_driver'
libwdi:info [wdi_prepare_driver] Successfully created 'C:\Users\Breno\usb_driver\WUP-028.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:info [wdi_prepare_driver] Test signing is: Disabled
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Breno\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Breno\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'wup-028.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Breno\usb_driver\wup-028.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Breno\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Breno\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] Successfully created file 'C:\Users\Breno\usb_driver\WUP-028.cat'
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'Root' store
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'TrustedPublisher' store
libwdi:debug [CreateSelfSignedCert] Set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] Created new key container
libwdi:debug [CreateSelfSignedCert] Generated new keypair...
libwdi:info [CreateSelfSignedCert] Created new self-signed certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:debug [SelfSignFile] Successfully created certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:info [SelfSignFile] Added certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] Successfully signed file 'C:\Users\Breno\usb_driver\WUP-028.cat'
libwdi:info [SelfSignFile] Successfully deleted private key
Installing driver. Please wait...
libwdi:debug [wdi_install_driver] Using progress bar mode
libwdi:debug [installer process] got parameter WUP-028.inf
libwdi:debug [process_message] Got request for device_id
libwdi:debug [installer process] got device_id: 'USB\VID_057E&PID_0337\15/07/2014'
libwdi:debug [process_message] Got request for hardware_id
libwdi:debug [installer process] got hardware_id: 'USB\VID_057E&PID_0337&REV_0100'
libwdi:debug [installer process] got user_sid: 'S-1-5-21-4243926853-2526766750-2228146468-1002'
libwdi:debug [installer process] using syslog 'C:\WINDOWS\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [installer process] Installing driver for USB\VID_057E&PID_0337&REV_0100 - please wait...
libwdi:debug [syslog] eno\usb_driver\installer_x64.exe" "WUP-028.inf"
libwdi:debug [syslog] on Restrictions Policy Check]
libwdi:debug [syslog] >>>  Section start 2021/12/26 13:06:49.218
libwdi:debug [syslog] <<  Section end 2021/12/26 13:10:23.939
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Installation Restrictions Policy Check]
libwdi:debug [syslog] >>>  Section start 2021/12/26 13:05:31.113
libwdi:debug [syslog] 909
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Installation Restrictions Policy Check]
libwdi:debug [syslog] >>>  Section start 2021/12/26 13:02:01.090
libwdi:debug [syslog] <<<  Section end 2021/12/26 13:07:28.001
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2021/12/26 13:04:52.392
libwdi:debug [syslog]       cmd: "C:\Users\Breno\usb_driver\installer_x64.exe" "WUP-028.inf"
libwdi:debug [syslog] r_x64.exe" "WUP-028.inf"
libwdi:debug [syslog] 6 12:58:56.462
libwdi:debug [syslog]       cmd: "C:\Users\Breno\usb_driver\installer_x64.exe" "WUP-028.inf"
libwdi:debug [syslog] reno\usb_driver\wup-028.inf} 14:46:45.826
libwdi:debug [syslog]      sto:                Driver Package = c:\users\breno\usb_driver\wup-028.inf
libwdi:debug [syslog]      sto:                Flags          = 0x00000007
libwdi:debug [syslog]      sto:                Destination    = C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}
libwdi:debug [syslog]      sto:                Copying driver package files to 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}'.
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT} 14:46:45.873
libwdi:debug [syslog]      flq:                     Copying 'c:\users\breno\usb_driver\amd64\WdfCoInstaller01011.dll' to 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                     Copying 'c:\users\breno\usb_driver\amd64\WinUSBCoInstaller2.dll' to 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                     Copying 'c:\users\breno\usb_driver\WUP-028.cat' to 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                     Copying 'c:\users\breno\usb_driver\wup-028.inf' to 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\wup-028.inf'.
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT - exit(0x00000000)} 14:46:45.930
libwdi:debug [syslog]      sto:           {Copy Driver Package: exit(0x00000000)} 14:46:45.939
libwdi:debug [syslog]      ump:           Import flags: 0x00000000
libwdi:debug [syslog]      pol:           {Driver package policy check} 14:46:45.955
libwdi:debug [syslog]      pol:           {Driver package policy check - exit(0x00000000)} 14:46:45.957
libwdi:debug [syslog]      sto:           {Stage Driver Package: C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\wup-028.inf} 14:46:45.959
libwdi:debug [syslog]      inf:                Provider       = libwdi
libwdi:debug [syslog]      inf:                Class GUID     = {88bae032-5a81-49f0-bc3d-a4ff138216d6}
libwdi:debug [syslog]      inf:                Driver Version = 06/02/2012,6.1.7600.16385
libwdi:debug [syslog]      inf:                Catalog File   = WUP-028.cat
libwdi:debug [syslog]      inf:                Version Flags  = 0x00000011
libwdi:debug [syslog]      inf:                {Query Configurability: C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\wup-028.inf} 14:46:45.974
libwdi:debug [syslog]      inf:                     Driver package uses WDF.
libwdi:debug [syslog]      inf:                     Driver package 'wup-028.inf' is configurable.
libwdi:debug [syslog]      inf:                {Query Configurability: exit(0x00000000)} 14:46:45.979
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT} 14:46:45.981
libwdi:debug [syslog]      flq:                     Copying 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\amd64\WdfCoInstaller01011.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                     Copying 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\amd64\WinUSBCoInstaller2.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                     Copying 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\WUP-028.cat' to 'C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                     Copying 'C:\Users\Breno\AppData\Local\Temp\{51513e76-25ce-ac46-867a-37736311efc5}\wup-028.inf' to 'C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\wup-028.inf'.
libwdi:debug [syslog]      flq:                {FILE_QUEUE_COMMIT - exit(0x00000000)} 14:46:46.052
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE} 14:46:46.053
libwdi:debug [syslog]      sig:                     Driver package catalog is valid.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 14:46:46.077
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\WUP-028.cat
libwdi:debug [syslog] !    sig:                          Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                          Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 14:46:46.088
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 14:46:46.091
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{b54dbad8-4af8-3748-a7be-798e1675e629}\WUP-028.cat
libwdi:debug [syslog] !    sig:                          Verifying file against specific Authenticode(tm) catalog failed.
libwdi:debug [syslog] !    sig:                          Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 14:46:46.101
libwdi:debug [syslog] !!!  sig:                     Driver package catalog file certificate does not belong to Trusted Root Certificates, and Code Integrity is enforced.
libwdi:debug [syslog] !!!  sig:                     Driver package failed signature validation. Error = 0x800B0109
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE: exit(0x800b0109)} 14:46:46.107
libwdi:debug [syslog] !!!  sig:                Driver package failed signature verification. Error = 0x800B0109
libwdi:debug [syslog] !!!  sto:                Failed to import driver package into Driver Store. Error = 0x800B0109
libwdi:debug [syslog]      sto:           {Stage Driver Package: exit(0x800b0109)} 14:46:46.113
libwdi:debug [syslog]      sto:      {Setup Import Driver Package - exit (0x800b0109)} 14:46:46.126
libwdi:debug [syslog] !!!  ndv:      Driver package import failed for device.
libwdi:debug [syslog]      ndv: {Update Device Driver - exit(00000109)}
libwdi:debug [syslog] !!!  ndv: Failed to install device instance 'USB\VID_057E&PID_0337\15/07/2014'. Error = 0x00000109
libwdi:debug [process_message] Switching timeout back to finite
libwdi:debug [installer process] This version of Windows is refusing to trust the installed certificate.
libwdi:debug [process_message] Installer process completed
Driver Installation: FAILED (Operation not supported or not implemented)
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0D8C&PID_0012&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0d8c&Class_01&SubClass_01&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] usbaudio USB device (0): USB\VID_0D8C&PID_0012&MI_00\8&1CFDE082&0&0000
libwdi:debug [wdi_create_list] Device description: 'USB Audio Device (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_28DE&PID_2000&REV_0101&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_28de&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (2): USB\VID_28DE&PID_2000&MI_01\8&39134F64&2&0001
libwdi:debug [wdi_create_list] Device description: 'Lighthouse FPGA RX (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0043&REV_0200&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (4): USB\VID_1532&PID_0043&MI_02\6&22A5C314&0&0002
libwdi:debug [wdi_create_list] Device description: 'Razer DeathAdder Chroma (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0BB4&PID_2C87&REV_0200
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0BB4&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (5): USB\VID_0BB4&PID_2C87\207B356C5548
libwdi:debug [wdi_create_list] Device description: 'HTC Vive'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_28DE&PID_2101&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_28DE&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (7): USB\VID_28DE&PID_2101\2D4128D200
libwdi:debug [wdi_create_list] Device description: 'Watchman Dongle'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_057E&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (8): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0BB4&PID_0306&REV_0112
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0BB4&Class_FF&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 12.0.1.917
libwdi:debug [wdi_create_list] BTWUSB USB device (9): USB\VID_0BB4&PID_0306\807ABF4A54AC
libwdi:debug [wdi_create_list] Device description: 'BCM920703 Bluetooth 4.1'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_12BA&PID_0033&REV_0223&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_12ba&Class_01&SubClass_01&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] usbaudio USB device (10): USB\VID_12BA&PID_0033&MI_00\6&3107B9C4&0&0000
libwdi:debug [wdi_create_list] Device description: 'Wired USB Headset (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0241&REV_0200&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 6.2.9200.16516
libwdi:debug [wdi_create_list] HidUsb USB device (11): USB\VID_1532&PID_0241&MI_02\6&164F975&1&0002
libwdi:debug [wdi_create_list] Device description: 'Razer BlackWidow (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0241&REV_0200&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_00&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.15063.0
libwdi:debug [wdi_create_list] HidUsb USB device (12): USB\VID_1532&PID_0241&MI_01\6&164F975&1&0001
libwdi:debug [wdi_create_list] Device description: 'Razer BlackWidow (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0241&REV_0200&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (13): USB\VID_1532&PID_0241&MI_00\6&164F975&1&0000
libwdi:debug [wdi_create_list] Device description: 'Razer BlackWidow (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0D8C&PID_0012&REV_0100&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0d8c&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (17): USB\VID_0D8C&PID_0012&MI_03\8&1CFDE082&0&0003
libwdi:debug [wdi_create_list] Device description: 'USB Audio Device (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0BB4&PID_2C87&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0bb4&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] usbvideo USB device (18): USB\VID_0BB4&PID_2C87&MI_00\8&827B5E9&0&0000
libwdi:debug [wdi_create_list] Device description: 'HTC Vive (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0C45&PID_64AB&REV_0527&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0c45&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] usbvideo USB device (21): USB\VID_0C45&PID_64AB&MI_00\6&1145BDAD&0&0000
libwdi:debug [wdi_create_list] Device description: 'Integrated Camera (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0043&REV_0200&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (22): USB\VID_1532&PID_0043&MI_00\6&22A5C314&0&0000
libwdi:debug [wdi_create_list] Device description: 'Razer DeathAdder Chroma (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0424&PID_274D&REV_0200&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0424&Class_02&SubClass_02&Prot_01
libwdi:debug [wdi_create_list] Driver version: 1.0.0.0
libwdi:debug [wdi_create_list] usbser USB device (23): USB\VID_0424&PID_274D&MI_00\7&2E7C9416&0&0000
libwdi:debug [wdi_create_list] Device description: 'USB5734 COM Port (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_28DE&PID_2000&REV_0101&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_28de&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (26): USB\VID_28DE&PID_2000&MI_00\8&39134F64&2&0000
libwdi:debug [wdi_create_list] Device description: 'HID (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_050D&PID_065A&REV_0112
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_050D&Class_FF&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 12.0.1.410
libwdi:debug [wdi_create_list] BTHUSB USB device (27): USB\VID_050D&PID_065A\5CF3708B3348
libwdi:debug [wdi_create_list] Device description: 'BCM20702A0'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_12BA&PID_0033&REV_0223&MI_03
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_12ba&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (30): USB\VID_12BA&PID_0033&MI_03\6&3107B9C4&0&0003
libwdi:debug [wdi_create_list] Device description: 'Wired USB Headset (Interface 3)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_1532&PID_0043&REV_0200&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_1532&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 6.2.9200.16385
libwdi:debug [wdi_create_list] HidUsb USB device (31): USB\VID_1532&PID_0043&MI_01\6&22A5C314&0&0001
21 devices found.
libwdi:debug [wdi_create_list] Device description: 'Razer DeathAdder Chroma (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_28DE&PID_2101&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_28DE&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22523.1000
libwdi:debug [wdi_create_list] HidUsb USB device (32): USB\VID_28DE&PID_2101\20498E1EBF
libwdi:debug [wdi_create_list] Device description: 'Watchman Dongle'

**Comment by pbatard** [comment] 2021-12-26 17:55
Thanks but I'm afraid your log is missing some data, especially the Windows version you are using.

Therefore, I can only assume that you are using an insider build of Windows 11 rather than the release version, and that this is a duplicate of #242.

Zadig is not compatible with Windows 11 insider builds, and there's not much we can do to "fix" this, because, for Insider builds, Microsoft appear to have changed their mind about allowing driver packages signed by a certificate that belongs to Truster Publishers, from being installed.

This is why the log explicitly states:
```
This version of Windows is refusing to trust the installed certificate.
```

If you want to use Zadig, I will kindly ask that you use the formal release version of Windows 11 and not an insider build.

**Closed by pbatard** 2021-12-26 17:55 UTC

**Comment by jecassis** [comment] 2022-01-14 21:34
Quick tip: it is possible to use Zadig to install the USB device drivers on a Windows 11 Insider build by disabling driver signature enforcement temporarily. The driver install does persist after install and reboot which automatically reenables the signature enforcement. Note that disabling this feature is not without increased security and stability risks however since this is for an Insider build...
