### ISSUE TITLE
 The computer does not see the device!

### ISSUE THREAD

**Issue by Nazarych** [pbatard/libwdi#77] opened 2017-02-02 11:20 UTC
Problem:
![1](https://cloud.githubusercontent.com/assets/25468911/22547341/ec58bfbc-e949-11e6-9711-894f5a51305f.jpg)
1
![2](https://cloud.githubusercontent.com/assets/25468911/22547372/020b3dd0-e94a-11e6-84a0-6d190edc7b4a.jpg)
2
![3](https://cloud.githubusercontent.com/assets/25468911/22547375/07a18560-e94a-11e6-8655-6f4c87bef1ba.jpg)
3
![4](https://cloud.githubusercontent.com/assets/25468911/22547388/0e2119aa-e94a-11e6-9d91-e2da000650ef.jpg)
4
![1](https://cloud.githubusercontent.com/assets/25468911/22547437/42fbcdfa-e94a-11e6-82e9-3fdf991566cd.jpg)
This happened after I chose this item:
![5](https://cloud.githubusercontent.com/assets/25468911/22547452/543c655c-e94a-11e6-8947-529887c4358c.jpg)

**Comment by Nazarych** [comment] 2017-02-02 11:23
The device is turned on the USB port

**Comment by pbatard** [comment] 2017-02-02 11:28
You are misunderstanding what you see.

You can __ALWAYS__ install a __WCID__ driver (which is a generic driver part, that is not associated with any device), so the issue is __NOT__ that Zadig is listing your device as a blank entry, against which you can still install the driver, but that you are installing the global WCID driver.

Please be aware that, by default, Zadig does __NOT__ list devices that already have a driver installed, __which is the case for your device__ (because it is listed under the "Ports" category).

So you first need to tell Zadig to show devices that __already__ had a driver installed, by going to _Options_ &rarr; _List All Devices_, and then you will find your USBasp device in the list, and you can install the driver for it.

As I believe I have answered your question, I will close this issue.

**Closed by pbatard** 2017-02-02 11:28 UTC

**Comment by Nazarych** [comment] 2017-02-02 11:38
Thanks for the answer! Last question: what driver you need to install flash to Transistir-tester?

**Comment by pbatard** [comment] 2017-02-02 11:39
I don't know. I don't know anything about that device.

**Comment by Nazarych** [comment] 2017-02-02 11:40
Thank you very much!

**Comment by AlexMaass** [comment] 2017-02-07 02:01
Hi, I am trying to get my gamecube controller adapter to work with zadig, I have had the same problem as Nazarych here. I have selected all devices and nothing shows up. This is driving me insane, can you offer me any solutions? Much appreciated!

**Comment by pbatard** [comment] 2017-02-07 10:02
Do you see your device in Windows' Device Manager? What's its name there?

Please post a screenshot from Device Manager showing your device. Unless you see it there, and it's an USB device, it will never show in Zadig.

**Comment by Nazarych** [comment] 2017-02-07 10:25
Options-List all devices  

Choose your programmer and stitch
