### ISSUE TITLE
Zadig displays driver installation failed when trying to replace wup-028

### ISSUE THREAD

**Issue by Plasmello** [pbatard/libwdi#292] opened 2023-07-11 19:21 UTC
```
Zadig 2.8.782
Windows 11 Pro, 64-bit (Build 22621.1848)
ini file 'zadig.ini' not found in '\\Mac\Home\Downloads' - default parameters will be used
default driver set to 'WinUSB'
0 devices found.
10 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFA&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203A&Class_07&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.900
libwdi:debug [wdi_create_list] usbprint USB device (0): USB\VID_203A&PID_FFFA\TAG30C7B7018
libwdi:debug [wdi_create_list] Device description: 'Virtual Printer (EPSON ET-2760 Series)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFB&REV_0110&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_203A&PID_FFFB&MI_01\6&8A7A4EF&0&0001
libwdi:debug [wdi_create_list] Device description: 'Virtual Keyboard Interface (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFB&REV_0110&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (2): USB\VID_203A&PID_FFFB&MI_00\6&8A7A4EF&0&0000
libwdi:debug [wdi_create_list] Device description: 'Virtual Keyboard Interface (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_057E&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (4): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (6): USB\VID_203A&PID_FFFC&MI_00\6&100686D9&0&0000
libwdi:debug [wdi_create_list] Device description: 'Absolute Coordinate Interface (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (7): USB\VID_203A&PID_FFFC&MI_01\6&100686D9&0&0001
libwdi:debug [wdi_create_list] Device description: 'Relative Coordinate Interface (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFF9&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.608
libwdi:debug [wdi_create_list] usbvideo USB device (8): USB\VID_203A&PID_FFF9&MI_00\6&13458A23&0&0000
libwdi:debug [wdi_create_list] Device description: 'FaceTime HD Camera (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFA&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203A&Class_07&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.900
libwdi:debug [wdi_create_list] usbprint USB device (9): USB\VID_203A&PID_FFFA\TAG31D87ACA0
libwdi:debug [wdi_create_list] Device description: 'Virtual Printer (Print to PDF (Mac Desktop))'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (10): USB\VID_203A&PID_FFFC&MI_02\6&100686D9&0&0002
libwdi:debug [wdi_create_list] Device description: 'Pen Interface (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFF9&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.608
libwdi:debug [wdi_create_list] usbvideo USB device (13): USB\VID_203A&PID_FFF9&MI_00\6&385108F9&0&0000
libwdi:debug [wdi_create_list] Device description: 'Bryan Camera (Interface 0)'
Using inf name: WUP-028.inf
Successfully extracted driver files.
libwdi:info [extract_binaries] Successfully extracted driver files to 'C:\Users\bryan\usb_driver'
libwdi:info [wdi_prepare_driver] Successfully created 'C:\Users\bryan\usb_driver\WUP-028.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:info [wdi_prepare_driver] Test signing is: Disabled
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\bryan\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\bryan\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'wup-028.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\bryan\usb_driver\wup-028.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\bryan\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\bryan\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] Successfully created file 'C:\Users\bryan\usb_driver\WUP-028.cat'
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'Root' store
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'TrustedPublisher' store
libwdi:debug [CreateSelfSignedCert] Set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] Created new key container
libwdi:debug [CreateSelfSignedCert] Generated new keypair...
libwdi:info [CreateSelfSignedCert] Created new self-signed certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:debug [SelfSignFile] Successfully created certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:info [SelfSignFile] Added certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] Successfully signed file 'C:\Users\bryan\usb_driver\WUP-028.cat'
libwdi:info [SelfSignFile] Successfully deleted private key
Installing driver. Please wait...
libwdi:debug [wdi_install_driver] Using progress bar mode
libwdi:debug [installer process] got parameter WUP-028.inf
libwdi:debug [process_message] Got request for device_id
libwdi:debug [installer process] got device_id: 'USB\VID_057E&PID_0337\15/07/2014'
libwdi:debug [process_message] Got request for hardware_id
libwdi:debug [installer process] got hardware_id: 'USB\VID_057E&PID_0337&REV_0100'
libwdi:debug [installer process] got user_sid: 'S-1-5-21-3872174525-2411003423-2386637986-1000'
libwdi:debug [installer process] using syslog 'C:\Windows\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [installer process] Installing driver for USB\VID_057E&PID_0337&REV_0100 - please wait...
libwdi:debug [syslog]  cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] >
libwdi:debug [syslog] >>>  [Device Installation Restrictions Policy Check]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:04:17.657
libwdi:debug [syslog] >>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:16.172
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not disabled.
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:16.172
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] ckage: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: C:\Windows\System32\DriverStore\FileRepository\xusb22.inf_arm64_6b364fdbc8dcd67a} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:      {Core Driver Package Delete: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto: {Unstage Driver Package: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:00.907
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:16.172
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not disabled.
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:16.172
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] it(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: C:\Windows\System32\DriverStore\FileRepository\xusb22.inf_arm64_6b364fdbc8dcd67a} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:      {Core Driver Package Delete: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto: {Unstage Driver Package: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:00.907
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:16.172
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not disabled.
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:16.172
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] all (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog]  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog] \bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [syslog]             Driver packages registered to 'microsoft_bluetooth_a2dp.inf':
libwdi:debug [syslog]      idb:                     microsoft_bluetooth_a2dp.inf_arm64_f83fdff832fbc903
libwdi:debug [syslog]      idb:           {Unregister Driver Package: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      cpy:           {Delete Directory: C:\Windows\System32\DriverStore\FileRepository\microsoft_bluetooth_a2dp.inf_arm64_188d3cfd7f8b1d30} 15:01:00.892
libwdi:debug [syslog]      cpy:           {Delete Directory: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END} 15:01:00.892
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      sto:      {Core Driver Package Delete: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      sto: {Unstage Driver Package: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      sto: {Unstage Driver Package: C:\Windows\System32\DriverStore\FileRepository\xusb22.inf_arm64_6b364fdbc8dcd67a\xusb22.inf} 15:01:00.892
libwdi:debug [syslog]      inf:      Provider       = Microsoft
libwdi:debug [syslog]      inf:      Class GUID     = {d61ca365-5af4-4486-998b-9db4734c6ca3}
libwdi:debug [syslog]      inf:      Driver Version = 09/26/2022,10.0.22621.608
libwdi:debug [syslog]      inf:      Version Flags  = 0x00000013
libwdi:debug [syslog]      sto:      {Core Driver Package Delete: xusb22.inf_arm64_6b364fdbc8dcd67a} 15:01:00.892
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE BEGIN} 15:01:00.892
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE BEGIN: exit(0x00000000)} 15:01:00.892
libwdi:debug [syslog]      idb:           {Unregister Driver Package: C:\Windows\System32\DriverStore\FileRepository\xusb22.inf_arm64_6b364fdbc8dcd67a\xusb22.inf} 15:01:00.892
libwdi:debug [syslog]      idb:                Unregistered driver package 'xusb22.inf_arm64_6b364fdbc8dcd67a' from 'xusb22.inf'.
libwdi:debug [syslog]      idb:                Deleted driver package object 'xusb22.inf_arm64_6b364fdbc8dcd67a' from DRIVERS database node.
libwdi:debug [syslog]      idb:                Driver packages registered to 'xusb22.inf':
libwdi:debug [syslog]      idb:                     xusb22.inf_arm64_4b255913a554fe19
libwdi:debug [syslog]      idb:           {Unregister Driver Package: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: C:\Windows\System32\DriverStore\FileRepository\xusb22.inf_arm64_6b364fdbc8dcd67a} 15:01:00.907
libwdi:debug [syslog]      cpy:           {Delete Directory: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END} 15:01:00.907
libwdi:debug [syslog]      sto:           {DRIVERSTORE DELETE END: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto:      {Core Driver Package Delete: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog]      sto: {Unstage Driver Package: exit(0x00000000)} 15:01:00.907
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:00.907
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:00.907
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Enable Device Install]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:01:16.172
libwdi:debug [syslog]       cmd: C:\Windows\winsxs\arm64_microsoft-windows-servicingstack_31bf3856ad364e35_10.0.22621.1771_none_e92ba14a42f362f8\TiWorker.exe -Embedding
libwdi:debug [syslog]      ump: DeviceInstall service is not disabled.
libwdi:debug [syslog]      ump: DeviceInstall service is not started.
libwdi:debug [syslog] <<<  Section end 2023/07/11 15:01:16.172
libwdi:debug [syslog] <<<  [Exit status: SUCCESS]
libwdi:debug [syslog] >>>  [Device Install (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2023/07/11 15:03:40.114
libwdi:debug [syslog]       cmd: "C:\Users\bryan\usb_driver\installer_arm64.exe" "WUP-028.inf"
libwdi:debug [process_message] Switching timeout back to finite
libwdi:debug [installer process] This version of Windows is refusing to trust the installed certificate.
libwdi:debug [process_message] Installer process completed
Driver Installation: FAILED (Operation not supported or not implemented)
10 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFA&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203A&Class_07&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.900
libwdi:debug [wdi_create_list] usbprint USB device (0): USB\VID_203A&PID_FFFA\TAG30C7B7018
libwdi:debug [wdi_create_list] Device description: 'Virtual Printer (EPSON ET-2760 Series)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFB&REV_0110&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_203A&PID_FFFB&MI_01\6&8A7A4EF&0&0001
libwdi:debug [wdi_create_list] Device description: 'Virtual Keyboard Interface (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFB&REV_0110&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (2): USB\VID_203A&PID_FFFB&MI_00\6&8A7A4EF&0&0000
libwdi:debug [wdi_create_list] Device description: 'Virtual Keyboard Interface (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_057E&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (4): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (6): USB\VID_203A&PID_FFFC&MI_00\6&100686D9&0&0000
libwdi:debug [wdi_create_list] Device description: 'Absolute Coordinate Interface (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_01
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (7): USB\VID_203A&PID_FFFC&MI_01\6&100686D9&0&0001
libwdi:debug [wdi_create_list] Device description: 'Relative Coordinate Interface (Interface 1)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFF9&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.608
libwdi:debug [wdi_create_list] usbvideo USB device (8): USB\VID_203A&PID_FFF9&MI_00\6&13458A23&0&0000
libwdi:debug [wdi_create_list] Device description: 'FaceTime HD Camera (Interface 0)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFA&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203A&Class_07&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.900
libwdi:debug [wdi_create_list] usbprint USB device (9): USB\VID_203A&PID_FFFA\TAG31D87ACA0
libwdi:debug [wdi_create_list] Device description: 'Virtual Printer (Print to PDF (Mac Desktop))'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFFC&REV_0100&MI_02
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_03&SubClass_00&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.819
libwdi:debug [wdi_create_list] HidUsb USB device (10): USB\VID_203A&PID_FFFC&MI_02\6&100686D9&0&0002
libwdi:debug [wdi_create_list] Device description: 'Pen Interface (Interface 2)'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_203A&PID_FFF9&REV_0100&MI_00
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_203a&Class_0e&SubClass_03&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.608
libwdi:debug [wdi_create_list] usbvideo USB device (13): USB\VID_203A&PID_FFF9&MI_00\6&385108F9&0&0000
libwdi:debug [wdi_create_list] Device description: 'Bryan Camera (Interface 0)'
```

**Comment by pbatard** [comment] 2023-07-11 19:46
> `ini file 'zadig.ini' not found in '\\Mac\Home\Downloads' - default parameters will be used`

You're using paralles on Mac. This is not supported.

Furthermore, since you're trying to install an ARM64 drive, this is a duplicate of #289.

**Closed by pbatard** 2023-07-11 19:46 UTC

**Comment by Plasmello** [comment] 2023-07-11 20:22
Well contrary to what you said, I just got it working. (I used some of your help from the past posts I saw you write.) For anyone looking for how, you basically have to disable TPM/Secure Boot on parallels to be able to use zadig after doing this, run this command with administrator in terminal: "bcdedit /set testsigning on" without quotes. After restarting, you should be able to use it.

**Comment by mcuee** [comment] 2023-08-09 01:56
> Well contrary to what you said, I just got it working. (I used some of your help from the past posts I saw you write.) For anyone looking for how, you basically have to disable TPM/Secure Boot on parallels to be able to use zadig after doing this, run this command with administrator in terminal: "bcdedit /set testsigning on" without quotes. After restarting, you should be able to use it.

Thanks for the updates. 

Once you need to use "bcdedit /set testsigning on", basically libwdi/Zadig is kind of losing its main benefits already. The aim of libwdi/Zadig is to be able to install driver without using the test mode.
