### ISSUE TITLE
Regarding libusbk driver Installation on Windows 10 ARM64 OS in Raspberry pi 4

### ISSUE THREAD

**Issue by Sourab1801** [pbatard/libwdi#264] opened 2022-06-24 10:29 UTC
hello @pbatard , I sourabh , Actally i am trying to install libusbk driver using zadig software. I am using Windows 10 ARM on Raspberry pi 4. So iam facing Error == Driver installation :FAILED (Attempting to use 32 bit installer on 64 bit system).
please tell how to face this issue.
Thank you.

**Comment by pbatard** [comment] 2022-06-24 10:52
Duplicate of #263, which is already answered. Please don't spam, or I will have to block you.
There is __no__ solution to your issue at the moment: you cannot install libusbK on Windows ARM64.

**Closed by pbatard** 2022-06-24 10:52 UTC

**Comment by mcuee** [comment] 2023-02-08 01:54
Reference here: there will be no libusbK.sys for Windows on ARM/ARM64. Please use WinUSB driver.
* https://github.com/mcuee/libusbk/issues/40
