### ISSUE TITLE
0xE0000246 when installing WinUSB 

### ISSUE THREAD

**Issue by wamwammiri** [pbatard/libwdi#115] opened 2018-02-20 19:49 UTC
I am trying to install WinUSB on my GC controller adapter but I keep running into this error. When I try it on a different computer, it works perfectly so I have no clue what the problem is, nobody else seems to have fixed this problem online I can't find any other threads that describe it the same way I have it either.
Not sure if anyone can help but it would be very appreciated!

```
Zadig 2.3.701
Windows 10 64-bit (Build 16299)
ini file 'zadig.ini' not found - default parameters will be used
default driver set to 'WinUSB'
2 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0CF3&PID_E301&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_E0&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driverless USB device (4): USB\VID_0CF3&PID_E301\5&12978346&0&4
libwdi:debug [wdi_create_list] could not read device description for 4: [#0000000D] The data is invalid.
libwdi:debug [wdi_create_list] Device description: 'Unknown Device #1'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driverless USB device (5): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
Using inf name: WUP-028.inf
Successfully extracted driver files.
Installing driver. Please wait...
libwdi:info [extract_binaries] successfully extracted driver files to C:\Users\Wamee\usb_driver
libwdi:info [wdi_prepare_driver] successfully created 'C:\Users\Wamee\usb_driver\WUP-028.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Wamee\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Wamee\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'wup-028.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Wamee\usb_driver\wup-028.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Wamee\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\Wamee\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] successfully created file 'C:\Users\Wamee\usb_driver\WUP-028.cat'
libwdi:info [RemoveCertFromStore] deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'Root' store
libwdi:info [RemoveCertFromStore] deleted existing certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' from 'TrustedPublisher' store
libwdi:debug [CreateSelfSignedCert] set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] created new key container
libwdi:debug [CreateSelfSignedCert] generated new keypair
libwdi:info [CreateSelfSignedCert] created new self-signed certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:debug [SelfSignFile] successfully created certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)'
libwdi:info [SelfSignFile] added certificate 'CN=USB\VID_057E&PID_0337 (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] successfully signed file 'C:\Users\Wamee\usb_driver\WUP-028.cat'
libwdi:info [SelfSignFile] successfully deleted private key
libwdi:debug [wdi_install_driver] using progress bar mode
libwdi:debug [installer process] got parameter WUP-028.inf
libwdi:debug [process_message] got request for device_id
libwdi:debug [installer process] got device_id: 'USB\VID_057E&PID_0337\15/07/2014'
libwdi:debug [process_message] got request for hardware_id
libwdi:debug [installer process] got hardware_id: 'USB\VID_057E&PID_0337&REV_0100'
libwdi:debug [installer process] got user_sid: 'S-1-5-21-3604198702-2103251238-99552763-1001'
libwdi:debug [installer process] using syslog 'C:\WINDOWS\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] switching timeout to infinite
libwdi:debug [installer process] Installing driver for USB\VID_057E&PID_0337&REV_0100 - please wait...
libwdi:debug [syslog] ll (UpdateDriverForPlugAndPlayDevices) - USB\VID_057E&PID_0337&REV_0100]
libwdi:debug [syslog] >>>  Section start 2018/02/20 14:44:47.305
libwdi:debug [syslog]       cmd: "C:\Users\Wamee\usb_driver\installer_x64.exe" "WUP-028.inf"
libwdi:debug [syslog]      ndv: INF path: C:\Users\Wamee\usb_driver\WUP-028.inf
libwdi:debug [syslog]      ndv: Install flags: 0x00000001
libwdi:debug [syslog]      ndv: {Update Device Driver - USB\VID_057E&PID_0337\15/07/2014}
libwdi:debug [syslog]      ndv:      Search options: 0x00000080
libwdi:debug [syslog]      ndv:      Searching single INF 'C:\Users\Wamee\usb_driver\WUP-028.inf'
libwdi:debug [syslog]      dvi:      {Build Driver List} 14:44:47.350
libwdi:debug [syslog]      dvi:           Searching for hardware ID(s):
libwdi:debug [syslog]      dvi:                usb\vid_057e&pid_0337&rev_0100
libwdi:debug [syslog]      dvi:                usb\vid_057e&pid_0337
libwdi:debug [syslog]      dvi:           Searching for compatible ID(s):
libwdi:debug [syslog]      dvi:                usb\class_03&subclass_00&prot_00
libwdi:debug [syslog]      dvi:                usb\class_03&subclass_00
libwdi:debug [syslog]      dvi:                usb\class_03
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE} 14:44:47.386
libwdi:debug [syslog]      sig:                Key      = wup-028.inf
libwdi:debug [syslog]      sig:                FilePath = c:\users\wamee\usb_driver\wup-028.inf
libwdi:debug [syslog]      sig:                Catalog  = c:\users\wamee\usb_driver\WUP-028.cat
libwdi:debug [syslog] !    sig:                Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 14:44:48.870
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE} 14:44:48.875
libwdi:debug [syslog]      sig:                Key      = wup-028.inf
libwdi:debug [syslog]      sig:                FilePath = c:\users\wamee\usb_driver\wup-028.inf
libwdi:debug [syslog]      sig:                Catalog  = c:\users\wamee\usb_driver\WUP-028.cat
libwdi:debug [syslog]      sig:                Success: File is signed in Authenticode(tm) catalog.
libwdi:debug [syslog]      sig:                Error 0xe0000241: The INF was signed with an Authenticode(tm) catalog from a trusted publisher.
libwdi:debug [syslog]      sig:           {_VERIFY_FILE_SIGNATURE exit(0xe0000241)} 14:44:48.900
libwdi:debug [syslog]      dvi:           Created Driver Node:
libwdi:debug [syslog]      dvi:                HardwareID   - USB\VID_057E&PID_0337
libwdi:debug [syslog]      dvi:                InfName      - c:\users\wamee\usb_driver\wup-028.inf
libwdi:debug [syslog]      dvi:                DevDesc      - WUP-028
libwdi:debug [syslog]      dvi:                Section      - USB_Install
libwdi:debug [syslog]      dvi:                Rank         - 0x00ff0001
libwdi:debug [syslog]      dvi:                Signer Score - Authenticode
libwdi:debug [syslog]      dvi:                DrvDate      - 02/10/2017
libwdi:debug [syslog]      dvi:                Version      - 6.1.7600.16385
libwdi:debug [syslog]      dvi:      {Build Driver List - exit(0x00000000)} 14:44:48.940
libwdi:debug [syslog]      dvi:      {DIF_SELECTBESTCOMPATDRV} 14:44:48.944
libwdi:debug [syslog]      dvi:           Default installer: Enter 14:44:48.948
libwdi:debug [syslog]      dvi:                {Select Best Driver}
libwdi:debug [syslog]      dvi:                     Class GUID of device changed to: {88bae032-5a81-49f0-bc3d-a4ff138216d6}.
libwdi:debug [syslog]      dvi:                     Selected Driver:
libwdi:debug [syslog]      dvi:                          Description - WUP-028
libwdi:debug [syslog]      dvi:                          InfFile     - c:\users\wamee\usb_driver\wup-028.inf
libwdi:debug [syslog]      dvi:                          Section     - USB_Install
libwdi:debug [syslog]      dvi:                {Select Best Driver - exit(0x00000000)}
libwdi:debug [syslog]      dvi:           Default installer: Exit
libwdi:debug [syslog]      dvi:      {DIF_SELECTBESTCOMPATDRV - exit(0x00000000)} 14:44:48.979
libwdi:debug [syslog]      ndv:      Force Installing Driver:
libwdi:debug [syslog]      ndv:           Inf Name       - wup-028.inf
libwdi:debug [syslog]      ndv:           Driver Date    - 02/10/2017
libwdi:debug [syslog]      ndv:           Driver Version - 6.1.7600.16385
libwdi:debug [syslog]      sto:      {Setup Import Driver Package: c:\users\wamee\usb_driver\wup-028.inf} 14:44:48.998
libwdi:debug [syslog]      inf:           Provider: libwdi
libwdi:debug [syslog]      inf:           Class GUID: {88bae032-5a81-49f0-bc3d-a4ff138216d6}
libwdi:debug [syslog]      inf:           Driver Version: 02/10/2017,6.1.7600.16385
libwdi:debug [syslog]      inf:           Catalog File: WUP-028.cat
libwdi:debug [syslog]      sto:           {Copy Driver Package: c:\users\wamee\usb_driver\wup-028.inf} 14:44:49.018
libwdi:debug [syslog]      sto:                Driver Package = c:\users\wamee\usb_driver\wup-028.inf
libwdi:debug [syslog]      sto:                Flags          = 0x00000007
libwdi:debug [syslog]      sto:                Destination    = C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}
libwdi:debug [syslog]      sto:                Copying driver package files to 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\wamee\usb_driver\amd64\WdfCoInstaller01011.dll' to 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\wamee\usb_driver\amd64\WinUSBCoInstaller2.dll' to 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\wamee\usb_driver\WUP-028.cat' to 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                Copying 'c:\users\wamee\usb_driver\wup-028.inf' to 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\wup-028.inf'.
libwdi:debug [syslog]      sto:           {Copy Driver Package: exit(0x00000000)} 14:44:49.067
libwdi:debug [syslog]      pol:           {Driver package policy check} 14:44:49.073
libwdi:debug [syslog]      pol:           {Driver package policy check - exit(0x00000000)} 14:44:49.073
libwdi:debug [syslog]      sto:           {Stage Driver Package: C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\wup-028.inf} 14:44:49.074
libwdi:debug [syslog]      inf:                {Query Configurability: C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\wup-028.inf} 14:44:49.078
libwdi:debug [syslog]      inf:                     Driver package uses WDF.
libwdi:debug [syslog]      inf:                     Driver package 'wup-028.inf' is configurable.
libwdi:debug [syslog]      inf:                {Query Configurability: exit(0x00000000)} 14:44:49.082
libwdi:debug [syslog]      flq:                Copying 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\amd64\WdfCoInstaller01011.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\amd64\WdfCoInstaller01011.dll'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\amd64\WinUSBCoInstaller2.dll' to 'C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\amd64\WinUSBCoInstaller2.dll'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\WUP-028.cat' to 'C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\WUP-028.cat'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\Wamee\AppData\Local\Temp\{bbb64a40-f813-554c-aa8b-d92b446c4c9b}\wup-028.inf' to 'C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\wup-028.inf'.
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE} 14:44:49.142
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 14:44:49.158
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\WUP-028.cat
libwdi:debug [syslog] !    sig:                          Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                          Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 14:44:49.163
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE} 14:44:49.164
libwdi:debug [syslog]      sig:                          Key      = wup-028.inf
libwdi:debug [syslog]      sig:                          FilePath = C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\wup-028.inf
libwdi:debug [syslog]      sig:                          Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\WUP-028.cat
libwdi:debug [syslog]      sig:                          Success: File is signed in Authenticode(tm) catalog.
libwdi:debug [syslog]      sig:                          Error 0xe0000241: The INF was signed with an Authenticode(tm) catalog from a trusted publisher.
libwdi:debug [syslog]      sig:                     {_VERIFY_FILE_SIGNATURE exit(0xe0000241)} 14:44:49.170
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT VALIDATE: exit(0x00000000)} 14:44:49.202
libwdi:debug [syslog]      sig:                Signer Score = 0x0F000000
libwdi:debug [syslog]      sig:                Signer Name  = USB\VID_057E&PID_0337 (libwdi autogenerated)
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT BEGIN} 14:44:49.205
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT BEGIN: exit(0x00000000)} 14:44:49.206
libwdi:debug [syslog]      cpy:                {Copy Directory: C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}} 14:44:49.206
libwdi:debug [syslog]      cpy:                     Target Path = C:\WINDOWS\System32\DriverStore\FileRepository\wup-028.inf_amd64_a33d370b4f7b9099
libwdi:debug [syslog]      cpy:                     {Copy Directory: C:\WINDOWS\System32\DriverStore\Temp\{0b9901d2-6c19-c048-bde0-c35d7c6de331}\amd64} 14:44:49.208
libwdi:debug [syslog]      cpy:                          Target Path = C:\WINDOWS\System32\DriverStore\FileRepository\wup-028.inf_amd64_a33d370b4f7b9099\amd64
libwdi:debug [syslog]      cpy:                     {Copy Directory: exit(0x00000000)} 14:44:49.211
libwdi:debug [syslog]      cpy:                {Copy Directory: exit(0x00000000)} 14:44:49.213
libwdi:debug [syslog]      idb:                {Register Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\wup-028.inf_amd64_a33d370b4f7b9099\wup-028.inf} 14:44:49.214
libwdi:debug [syslog]      idb:                     Created driver package object 'wup-028.inf_amd64_a33d370b4f7b9099' in SYSTEM database node.
libwdi:debug [syslog]      idb:                     Created driver INF file object 'oem76.inf' in SYSTEM database node.
libwdi:debug [syslog]      idb:                     Registered driver package 'wup-028.inf_amd64_a33d370b4f7b9099' with 'oem76.inf'.
libwdi:debug [syslog]      idb:                {Register Driver Package: exit(0x00000000)} 14:44:49.217
libwdi:debug [syslog]      idb:                {Publish Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\wup-028.inf_amd64_a33d370b4f7b9099\wup-028.inf} 14:44:49.217
libwdi:debug [syslog]      idb:                     Activating driver package 'wup-028.inf_amd64_a33d370b4f7b9099'.
libwdi:debug [syslog]      cpy:                     Published 'wup-028.inf_amd64_a33d370b4f7b9099\wup-028.inf' to 'oem76.inf'.
libwdi:debug [syslog]      idb:                     Indexed 2 device IDs for 'wup-028.inf_amd64_a33d370b4f7b9099'.
libwdi:debug [syslog] !    sto:                     Ignoring changes to inbox device class {88bae032-5a81-49f0-bc3d-a4ff138216d6} through ClassInstall32 section.
libwdi:debug [syslog]      sto:                     Flushed driver database node 'SYSTEM'. Time = 1390 ms
libwdi:debug [syslog]      idb:                {Publish Driver Package: exit(0x00000000)} 14:44:50.619
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT END} 14:44:50.625
libwdi:debug [syslog]      dvi:                     Flushed all driver package files to disk. Time = 188 ms
libwdi:debug [syslog]      sig:                     Installed catalog 'WUP-028.cat' as 'oem76.cat'.
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT END: exit(0x00000000)} 14:44:50.821
libwdi:debug [syslog]      sto:           {Stage Driver Package: exit(0x00000000)} 14:44:50.826
libwdi:debug [syslog]      sto:      {Setup Import Driver Package - exit (0x00000000)} 14:44:50.862
libwdi:debug [syslog]      dvi:      Searching for hardware ID(s):
libwdi:debug [syslog]      dvi:           usb\vid_057e&pid_0337&rev_0100
libwdi:debug [syslog]      dvi:           usb\vid_057e&pid_0337
libwdi:debug [process_message] switching timeout back to finite
libwdi:debug [installer process] unhandled error 0xE0000246 (-536870330)
libwdi:debug [installer process] [3758096966] One of the installers for this device cannot perform the installation at this time.
libwdi:debug [process_message] installer process completed
Driver Installation: FAILED (Other error)
2 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0CF3&PID_E301&REV_0001
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_E0&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driverless USB device (4): USB\VID_0CF3&PID_E301\5&12978346&0&4
libwdi:debug [wdi_create_list] could not read device description for 4: [#0000000D] The data is invalid.
libwdi:debug [wdi_create_list] Device description: 'Unknown Device #1'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driverless USB device (5): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
Saved file as 'C:\Users\Wamee\Downloads\zadig.log'
```

**Comment by pbatard** [comment] 2018-02-23 14:38
This looks like a Windows environment error (which seems to be confirmed by the fact that you're not seeing this error on other Windows platforms).

Considering the underlying error (`One of the installers for this device cannot perform the installation at this time.`) and the fact that, from what I can see, nobody seems to have a good solution for it apart from performing a clean reinstall of Windows, it all seems to point to your environment having either gotten corrupted or misconfigured. And I'm afraid this makes it very difficult to troubleshoot...

**Comment by wamwammiri** [comment] 2018-02-24 16:14
I was afraid that would be the case, thank you though!

**Comment by pbatard** [comment] 2018-02-24 16:24
Okay. I'm going to close this issue then (which won't prevent people from commenting on it, if they run into the same problem and can venture a solution).

**Closed by pbatard** 2018-02-24 16:24 UTC

**Comment by milomai** [comment] 2024-08-26 03:41
Maybe is Windows settings forbidden install device. Check this [question](https://answers.microsoft.com/en-us/windows/forum/all/one-of-the-installers-for-this-device-cannot/2df01216-cdbc-42e7-b5c7-c25768efde79) in Microsoft Support Community
