### ISSUE TITLE
Adapter not detected on AMD Ryzen running Windows 7.

### ISSUE THREAD

**Issue by wantija** [pbatard/libwdi#150] opened 2019-01-04 09:23 UTC
Having an issue using the official Gamecube controller adapter on Ryzen systems running Windows 7.
Followed the steps on the Dolphin Wiki
(https://wiki.dolphin-emu.org/index.php?title=How_to_use_the_Official_GameCube_Controller_Adapter_for_Wii_U_in_Dolphin)
and it is not detected in dolphin unable to get inputs from the controller, while on Windows 10 it is detected perfectly fine. Any chance this is an issue with libwdi and AMD Ryzen's USB driver for Windows 7? It worked perfectly under x58 and B250 platforms running Windows 7 and 10.

**Comment by pbatard** [comment] 2019-01-04 14:20
> and it is not detected in dolphin

Did you get an error in Zadig?

Please provide your complete installation log (Options &rarr; Advanced Mode). I can't help you without the log.

> Any chance this is an issue with libwdi and AMD Ryzen's USB driver for Windows 7?

Unlikely. All libwdi does is install third party drivers, which we did not develop. In other words, it simply automates the process you could complete manually, of installing one of the WinUSB, libusb-win32 or libusbK drivers. If, after the driver was successfully installed (i.e. Zadig did not report an error during tha process), your software is still unable to access the hardware, and you didn't receive an error from libwdi during driver installation, then the problem is purely outside of libwdi.

**Comment by wantija** [comment] 2019-01-04 18:34
Uninstalled and reinstalled, still getting the same error. Hopefully the log helps, guess I'll submit it to the Dolphin devs so they can look into it too.
[Zadig.log](https://github.com/pbatard/libwdi/files/2728103/Zadig.log)

**Comment by pbatard** [comment] 2019-01-04 18:56
Well, from what I can see from the log, the WinUSB driver was successfully installed against your device, and indeed, on refresh of the device list, Zadig does list your device as being handled by WinUSB:
```
ibwdi:debug [wdi_create_list] Hardware ID: USB\VID_057E&PID_0337&REV_0100
libwdi:debug [wdi_create_list] Compatible ID: USB\Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 6.1.7600.16385
libwdi:debug [wdi_create_list] WinUSB USB device (5): USB\VID_057E&PID_0337\15/07/2014
libwdi:debug [wdi_create_list] Device description: 'WUP-028'
```

I'm afraid that this means that whatever your issue is, it has nothing to do with libwdi/Zadig, as you would get the exact same result if you had installed the driver manually (again, all Zadig does is automate a task that you can totally do manually if you know how to).

There's really nothing for me to do here, so I have no choice but to close the issue. If your device doesn't work, it's either an issue with your hardware or with the application accessing it (in this case Dolphin).

**Closed by pbatard** 2019-01-04 18:56 UTC
