### ISSUE TITLE
running zadig 2.1.1 list all devices 

### ISSUE THREAD

**Issue by awolf10421** [pbatard/libwdi#41] opened 2015-01-04 01:04 UTC
running zadig 2.1.1 and trying to list all devices, dongle is pluged in and has installed driver on windows 7 machine. zadig is set to WinUSB but seems to seach and seach withut finding any device

**Comment by pbatard** [comment] 2015-01-14 15:48
This looks like a duplicate of #42. I will close this one and leave #41 open. Please try to apply the steps there.

**Closed by pbatard** 2015-01-14 15:48 UTC
