### ISSUE TITLE
Driver package failed signature verification. Error = 0xE0000243

### ISSUE THREAD

**Issue by maximus-sallam** [pbatard/libwdi#322] opened 2024-04-15 14:54 UTC
```
Zadig 2.8.782
Windows 11 Pro, 64-bit (Build 22631.3447)
ini file 'zadig.ini' not found in 'C:\Users\user.WINDOWS-ABCDEFG\Desktop' - default parameters will be used
default driver set to 'WinUSB'
0 devices found.
0 devices found.
5 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_0627&PID_0001\28754-0000:00:04.0-1
libwdi:debug [wdi_create_list] Device description: 'USB Tablet'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (2): USB\VID_0627&PID_0001\68284-0000:00:04.0-3
libwdi:debug [wdi_create_list] Device description: 'USB Keyboard'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (3): USB\VID_0627&PID_0001\89126-0000:00:04.0-2
libwdi:debug [wdi_create_list] Device description: 'USB Mouse'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_46F4&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_46F4&Class_08&SubClass_06&Prot_50
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.1
libwdi:debug [wdi_create_list] USBSTOR USB device (5): USB\VID_46F4&PID_0001\1-0000:00:04.0-4.1
libwdi:debug [wdi_create_list] Device description: 'USB HARDDRIVE'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_05C6&PID_9008&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_05C6&Class_FF&SubClass_FF&Prot_10
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] WINUSB USB device (6): USB\VID_05C6&PID_9008\5&341269D7&0&6
libwdi:debug [wdi_create_list] Device description: 'QUSB_BULK_CID:0439_SN:DA624029'
Using inf name: WinUSB_Generic_Device.inf
Successfully extracted driver files.
Installing driver. Please wait...
libwdi:info [extract_binaries] Successfully extracted driver files to 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver'
libwdi:info [wdi_prepare_driver] Successfully created 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\WinUSB_Generic_Device.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:info [wdi_prepare_driver] Test signing is: Disabled
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'winusb_generic_device.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\winusb_generic_device.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] Successfully created file 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\WinUSB_Generic_Device.cat'
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)' from 'Root' store
libwdi:info [RemoveCertFromStore] Deleted existing certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)' from 'TrustedPublisher' store
libwdi:debug [CreateSelfSignedCert] Set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] Created new key container
libwdi:debug [CreateSelfSignedCert] Generated new keypair...
libwdi:info [CreateSelfSignedCert] Created new self-signed certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)'
libwdi:debug [SelfSignFile] Successfully created certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)'
libwdi:info [SelfSignFile] Added certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] Successfully signed file 'C:\Users\user.WINDOWS-ABCDEFG\usb_driver\WinUSB_Generic_Device.cat'
libwdi:info [SelfSignFile] Successfully deleted private key
libwdi:debug [wdi_install_driver] Using progress bar mode
libwdi:debug [installer process] got parameter WinUSB_Generic_Device.inf
libwdi:debug [process_message] Got request for device_id
libwdi:debug [process_message] No device_id - sending empty string
libwdi:debug [installer process] got device_id: ''
libwdi:debug [process_message] Got request for hardware_id
libwdi:debug [process_message] No hardware_id - sending empty string
libwdi:debug [installer process] got hardware_id: ''
libwdi:debug [installer process] got user_sid: 'S-1-5-21-2549539947-1622164446-2286013990-1001'
libwdi:debug [installer process] using syslog 'C:\Windows\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [installer process] Copying inf file (for the next time device is plugged) - please wait...
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [syslog]         Driver package failed signature verification. Error = 0xE0000243
libwdi:debug [syslog] !!!  sto:           Failed to import driver package into Driver Store. Error = 0xE0000243
libwdi:debug [syslog]      sto:      {Stage Driver Package: exit(0xe0000243)} 09:36:34.995
libwdi:debug [syslog]      sto: {Setup Import Driver Package - exit (0xe0000243)} 09:36:34.995
libwdi:debug [syslog] !!!  inf: Failed to import driver package into driver store
libwdi:debug [syslog] !!!  inf: Error 0xe0000243: The publisher of an Authenticode(tm) signed catalog was not established as trusted.
libwdi:debug [syslog] inf:                Driver package 'USB_Serial_(CDC)_Generic_Device.inf' is configurable.
libwdi:debug [syslog] !    inf:                Driver package 'USB_Serial_(CDC)_Generic_Device.inf' has unresolved external dependencies.
libwdi:debug [syslog]      inf:           {Query Configurability: exit(0x00000000)} 09:36:34.964
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT} 09:36:34.964
libwdi:debug [syslog]      flq:                Copying 'C:\Users\USER~1.WIN\AppData\Local\Temp\{298a9c59-88e6-1a4c-a24c-782f45101e53}\USB_Serial_(CDC)_Generic_Device.cat' to 'C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.cat'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\USER~1.WIN\AppData\Local\Temp\{298a9c59-88e6-1a4c-a24c-782f45101e53}\USB_Serial_(CDC)_Generic_Device.inf' to 'C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.inf'.
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT - exit(0x00000000)} 09:36:34.979
libwdi:debug [syslog]      sto:           {DRIVERSTORE IMPORT VALIDATE} 09:36:34.979
libwdi:debug [syslog]      sig:                Driver package catalog is valid.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE} 09:36:34.979
libwdi:debug [syslog]      sig:                     Key      = USB_Serial_(CDC)_Generic_Device.inf
libwdi:debug [syslog]      sig:                     FilePath = C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.inf
libwdi:debug [syslog]      sig:                     Catalog  = C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.cat
libwdi:debug [syslog] !    sig:                     Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                     Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 09:36:34.995
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE} 09:36:34.995
libwdi:debug [syslog]      sig:                     Key      = USB_Serial_(CDC)_Generic_Device.inf
libwdi:debug [syslog]      sig:                     FilePath = C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.inf
libwdi:debug [syslog]      sig:                     Catalog  = C:\Windows\System32\DriverStore\Temp\{3a0acb8e-d56a-164d-9042-4b4a3c717c78}\USB_Serial_(CDC)_Generic_Device.cat
libwdi:debug [syslog]      sig:                     Success: File is signed in Authenticode(tm) catalog.
libwdi:debug [syslog]      sig:                     Error 0xe0000241: The INF was signed with an Authenticode(tm) catalog from a trusted publisher.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE exit(0xe0000241)} 09:36:34.995
libwdi:debug [syslog] !!!  sig:                Driver package signer is not trusted by system, and Code Integrity is enforced.
libwdi:debug [syslog] !!!  sig:                Driver package failed signature validation. Error = 0xE0000243
libwdi:debug [syslog]      sto:           {DRIVERSTORE IMPORT VALIDATE: exit(0xe0000243)} 09:36:34.995
libwdi:debug [syslog] !!!  sig:           Driver package failed signature verification. Error = 0xE0000243
libwdi:debug [syslog] !!!  sto:           Failed to import driver package into Driver Store. Error = 0xE0000243
libwdi:debug [syslog]      sto:      {Stage Driver Package: exit(0xe0000243)} 09:36:34.995
libwdi:debug [syslog]      sto: {Setup Import Driver Package - exit (0xe0000243)} 09:36:34.995
libwdi:debug [syslog] !!!  inf: Failed to import driver package into driver store
libwdi:debug [syslog] !!!  inf: Error 0xe0000243: The publisher of an Authenticode(tm) signed catalog was not established as trusted.
libwdi:debug [syslog] !!!  sig:                Driver package signer is not trusted by system, and Code Integrity is enforced.
libwdi:debug [syslog] !!!  sig:                Driver package failed signature validation. Error = 0xE0000243
libwdi:debug [syslog]      sto:           {DRIVERSTORE IMPORT VALIDATE: exit(0xe0000243)} 09:36:34.995
libwdi:debug [syslog] !!!  sig:           Driver package failed signature verification. Error = 0xE0000243
libwdi:debug [syslog] !!!  sto:           Failed to import driver package into Driver Store. Error = 0xE0000243
libwdi:debug [syslog]      sto:      {Stage Driver Package: exit(0xe0000243)} 09:36:34.995
libwdi:debug [syslog]      sto: {Setup Import Driver Package - exit (0xe0000243)} 09:36:34.995
libwdi:debug [syslog] !!!  inf: Failed to import driver package into driver store
libwdi:debug [syslog] !!!  inf: Error 0xe0000243: The publisher of an Authenticode(tm) signed catalog was not established as trusted.
libwdi:debug [process_message] Switching timeout back to finite
libwdi:debug [installer process] This version of Windows is refusing to trust the installed certificate.
libwdi:debug [process_message] Installer process completed
Driver Installation: FAILED (Operation not supported or not implemented)
5 devices found.
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_00&Prot_00
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (1): USB\VID_0627&PID_0001\28754-0000:00:04.0-1
libwdi:debug [wdi_create_list] Device description: 'USB Tablet'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_01&Prot_01
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (2): USB\VID_0627&PID_0001\68284-0000:00:04.0-3
libwdi:debug [wdi_create_list] Device description: 'USB Keyboard'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_0627&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_0627&Class_03&SubClass_01&Prot_02
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] HidUsb USB device (3): USB\VID_0627&PID_0001\89126-0000:00:04.0-2
libwdi:debug [wdi_create_list] Device description: 'USB Mouse'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_46F4&PID_0001&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_46F4&Class_08&SubClass_06&Prot_50
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.1
libwdi:debug [wdi_create_list] USBSTOR USB device (5): USB\VID_46F4&PID_0001\1-0000:00:04.0-4.1
libwdi:debug [wdi_create_list] Device description: 'USB HARDDRIVE'
libwdi:debug [wdi_create_list] Hardware ID: USB\VID_05C6&PID_9008&REV_0000
libwdi:debug [wdi_create_list] Compatible ID: USB\COMPAT_VID_05C6&Class_FF&SubClass_FF&Prot_10
libwdi:debug [wdi_create_list] Driver version: 10.0.22621.2506
libwdi:debug [wdi_create_list] WINUSB USB device (6): USB\VID_05C6&PID_9008\5&341269D7&0&6
libwdi:debug [wdi_create_list] Device description: 'QUSB_BULK_CID:0439_SN:DA624029'
```

**Comment by pbatard** [comment] 2024-04-15 15:19
1. You are installing the WCID driver but are running Windows 11. There is no need to install the WCID driver on Windows 11. Do you actually understand what the WCID driver is for?
2. I cannot replicate your issue on a standard Windows 11 x64 installation (see log below).
3. What happens if you try to install the driver against a USB device that is actually plugged in?
4. **YOUR CUSTOM ENVIRONMENT IS ACTUALLY VERY INTERESTING TO US**, because it appears to replicate the same Windows configuration conditions that Microsoft applies by default on ARM64, but not on x64, which we have been trying to figure out for months on account of #289. So it does look like you applied a custom configuration to your Windows installation that enables the same setting as Microsoft activates on Windows ARM64 but which we haven't been able to figure out. So if you can please tell us how you configured your Windows platform, and what additional Local Group Policy or security settings you might have applied, it would help use **immensely**, because, again, by the looks of it, you are using a custom Windows configuration that is different from vanilla Windows 11 x64, and, provided you still see the same issue when not installing the WCID driver, that is the root cause of your problem, so you will have to figure out how your installation of Windows differs from standard one to fix this anyway...

```
Zadig 2.8.782
Windows 11 Pro for Workstations, 64-bit (Build 22631.3447)
ini file 'zadig.ini' not found in 'C:\Users\pete\Desktop' - default parameters will be used
default driver set to 'WinUSB'
0 devices found.
Using inf name: WinUSB_Generic_Device.inf
Successfully extracted driver files.
Installing driver. Please wait...
libwdi:info [extract_binaries] Successfully extracted driver files to 'C:\Users\pete\usb_driver'
libwdi:info [wdi_prepare_driver] Successfully created 'C:\Users\pete\usb_driver\WinUSB_Generic_Device.inf'
libwdi:info [wdi_prepare_driver] Creating and self-signing a .cat file...
libwdi:info [wdi_prepare_driver] Test signing is: Disabled
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\pete\usb_driver\amd64\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\pete\usb_driver\amd64\winusbcoinstaller2.dll'
libwdi:debug [AddFileHash] 'winusb_generic_device.inf': INF type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\pete\usb_driver\winusb_generic_device.inf'
libwdi:debug [AddFileHash] 'wdfcoinstaller01011.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\pete\usb_driver\x86\wdfcoinstaller01011.dll'
libwdi:debug [AddFileHash] 'winusbcoinstaller2.dll': PE type
libwdi:info [ScanDirAndHash] added hash for 'C:\Users\pete\usb_driver\x86\winusbcoinstaller2.dll'
libwdi:info [CreateCat] Successfully created file 'C:\Users\pete\usb_driver\WinUSB_Generic_Device.cat'
libwdi:debug [CreateSelfSignedCert] Set Enhanced Key Usage, URL and CPS
libwdi:debug [CreateSelfSignedCert] Created new key container
libwdi:debug [CreateSelfSignedCert] Generated new keypair...
libwdi:info [CreateSelfSignedCert] Created new self-signed certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)'
libwdi:debug [SelfSignFile] Successfully created certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)'
libwdi:info [SelfSignFile] Added certificate 'CN=USB\MS_COMP_WINUSB (libwdi autogenerated)' to 'Root' and 'TrustedPublisher' stores
libwdi:info [SelfSignFile] Successfully signed file 'C:\Users\pete\usb_driver\WinUSB_Generic_Device.cat'
libwdi:info [SelfSignFile] Successfully deleted private key
libwdi:debug [wdi_install_driver] Using progress bar mode
libwdi:debug [installer process] got parameter WinUSB_Generic_Device.inf
libwdi:debug [process_message] Got request for device_id
libwdi:debug [process_message] No device_id - sending empty string
libwdi:debug [installer process] got device_id: ''
libwdi:debug [process_message] Got request for hardware_id
libwdi:debug [process_message] No hardware_id - sending empty string
libwdi:debug [installer process] got hardware_id: ''
libwdi:debug [installer process] got user_sid: 'S-1-5-21-1749556476-2293787269-1158594612-1001'
libwdi:debug [installer process] using syslog 'C:\WINDOWS\inf\setupapi.dev.log'
libwdi:debug [installer process] syslog reader thread started
libwdi:debug [installer process] successfully disabled the system restore point creation setting
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [installer process] Copying inf file (for the next time device is plugged) - please wait...
libwdi:debug [process_message] Switching timeout to infinite
libwdi:debug [syslog] tions Policy Check]
libwdi:debug [syslog] >>>  Section start 2024/04/15 16:04:23.020
libwdi:debug [syslog] ge: C:\Users\pete\usb_driver\WinUSB_Generic_Device.inf} 16:07:59.215
libwdi:debug [syslog]      sto:           Driver Package = C:\Users\pete\usb_driver\WinUSB_Generic_Device.inf
libwdi:debug [syslog]      sto:           Flags          = 0x00000007
libwdi:debug [syslog]      sto:           Destination    = C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}
libwdi:debug [syslog]      sto:           Copying driver package files to 'C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}'.
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT} 16:07:59.259
libwdi:debug [syslog]      flq:                Copying 'C:\Users\pete\usb_driver\WinUSB_Generic_Device.cat' to 'C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.cat'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\pete\usb_driver\WinUSB_Generic_Device.inf' to 'C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.inf'.
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT - exit(0x00000000)} 16:07:59.290
libwdi:debug [syslog]      sto:      {Copy Driver Package: exit(0x00000000)} 16:07:59.298
libwdi:debug [syslog]      ump:      Import flags: 0x00000000
libwdi:debug [syslog]      pol:      {Driver package policy check} 16:07:59.310
libwdi:debug [syslog]      pol:      {Driver package policy check - exit(0x00000000)} 16:07:59.311
libwdi:debug [syslog]      sto:      {Stage Driver Package: C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.inf} 16:07:59.312
libwdi:debug [syslog]      inf:           Provider       = libwdi
libwdi:debug [syslog]      inf:           Class GUID     = {88bae032-5a81-49f0-bc3d-a4ff138216d6}
libwdi:debug [syslog]      inf:           Driver Version = 06/02/2012,6.1.7600.16385
libwdi:debug [syslog]      inf:           Catalog File   = WinUSB_Generic_Device.cat
libwdi:debug [syslog]      inf:           Version Flags  = 0x00000011
libwdi:debug [syslog]      inf:           {Query Configurability: C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.inf} 16:07:59.344
libwdi:debug [syslog]      inf:                Driver package uses WDF.
libwdi:debug [syslog]      inf:                Driver package 'WinUSB_Generic_Device.inf' is configurable.
libwdi:debug [syslog]      inf:           {Query Configurability: exit(0x00000000)} 16:07:59.355
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT} 16:07:59.357
libwdi:debug [syslog]      flq:                Copying 'C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.cat' to 'C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.cat'.
libwdi:debug [syslog]      flq:                Copying 'C:\Users\pete\AppData\Local\Temp\{29d2aa3c-1258-3a42-b062-fe5bb4893035}\WinUSB_Generic_Device.inf' to 'C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.inf'.
libwdi:debug [syslog]      flq:           {FILE_QUEUE_COMMIT - exit(0x00000000)} 16:07:59.374
libwdi:debug [syslog]      sto:           {DRIVERSTORE IMPORT VALIDATE} 16:07:59.378
libwdi:debug [syslog]      sig:                Driver package catalog is valid.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE} 16:07:59.443
libwdi:debug [syslog]      sig:                     Key      = WinUSB_Generic_Device.inf
libwdi:debug [syslog]      sig:                     FilePath = C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.inf
libwdi:debug [syslog]      sig:                     Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.cat
libwdi:debug [syslog] !    sig:                     Verifying file against specific (valid) catalog failed.
libwdi:debug [syslog] !    sig:                     Error 0x800b0109: A certificate chain processed, but terminated in a root certificate which is not trusted by the trust provider.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE exit(0x800b0109)} 16:07:59.455
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE} 16:07:59.461
libwdi:debug [syslog]      sig:                     Key      = WinUSB_Generic_Device.inf
libwdi:debug [syslog]      sig:                     FilePath = C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.inf
libwdi:debug [syslog]      sig:                     Catalog  = C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}\WinUSB_Generic_Device.cat
libwdi:debug [syslog]      sig:                     Success: File is signed in Authenticode(tm) catalog.
libwdi:debug [syslog]      sig:                     Error 0xe0000241: The INF was signed with an Authenticode(tm) catalog from a trusted publisher.
libwdi:debug [syslog]      sig:                {_VERIFY_FILE_SIGNATURE exit(0xe0000241)} 16:07:59.538
libwdi:debug [syslog]      sto:           {DRIVERSTORE IMPORT VALIDATE: exit(0x00000000)} 16:07:59.544
libwdi:debug [syslog]      sig:           Signer Score  = 0x0F000000 (Authenticode)
libwdi:debug [syslog]      sig:           Signer Name   = USB\MS_COMP_WINUSB (libwdi autogenerated)
libwdi:debug [syslog]      sto:           {Core Driver Package Import: winusb_generic_device.inf_amd64_21c13ade83f2958f} 16:07:59.551
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT BEGIN} 16:07:59.552
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT BEGIN: exit(0x00000000)} 16:07:59.553
libwdi:debug [syslog]      cpy:                {Copy Directory: C:\WINDOWS\System32\DriverStore\Temp\{c73e765a-72ce-944d-b0f4-4ccce8c2be9e}} 16:07:59.554
libwdi:debug [syslog]      cpy:                     Target Path = C:\WINDOWS\System32\DriverStore\FileRepository\winusb_generic_device.inf_amd64_21c13ade83f2958f
libwdi:debug [syslog]      cpy:                {Copy Directory: exit(0x00000000)} 16:07:59.559
libwdi:debug [syslog]      idb:                {Register Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\winusb_generic_device.inf_amd64_21c13ade83f2958f\WinUSB_Generic_Device.inf} 16:07:59.560
libwdi:debug [syslog]      idb:                     Created driver package object 'winusb_generic_device.inf_amd64_21c13ade83f2958f' in SYSTEM database node.
libwdi:debug [syslog]      idb:                     Created driver INF file object 'oem42.inf' in SYSTEM database node.
libwdi:debug [syslog]      idb:                     Registered driver package 'winusb_generic_device.inf_amd64_21c13ade83f2958f' with 'oem42.inf'.
libwdi:debug [syslog]      idb:                {Register Driver Package: exit(0x00000000)} 16:07:59.569
libwdi:debug [syslog]      idb:                {Publish Driver Package: C:\WINDOWS\System32\DriverStore\FileRepository\winusb_generic_device.inf_amd64_21c13ade83f2958f\WinUSB_Generic_Device.inf} 16:07:59.569
libwdi:debug [syslog]      idb:                     Activating driver package 'winusb_generic_device.inf_amd64_21c13ade83f2958f'.
libwdi:debug [syslog]      cpy:                     Published 'winusb_generic_device.inf_amd64_21c13ade83f2958f\winusb_generic_device.inf' to 'oem42.inf'.
libwdi:debug [syslog]      idb:                     Indexed 2 device IDs for 'winusb_generic_device.inf_amd64_21c13ade83f2958f'.
libwdi:debug [syslog] !    sto:                     Ignoring changes to inbox device class {88bae032-5a81-49f0-bc3d-a4ff138216d6} through ClassInstall32 section.
libwdi:debug [syslog]      sto:                     Flushed driver database node 'SYSTEM'. Time = 0 ms
libwdi:debug [syslog]      idb:                {Publish Driver Package: exit(0x00000000)} 16:07:59.582
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT END} 16:07:59.586
libwdi:debug [syslog]      dvi:                     Flushed all driver package files to disk. Time = 2 ms
libwdi:debug [syslog]      sig:                     Installed catalog 'WinUSB_Generic_Device.cat' as 'oem42.cat'.
libwdi:debug [syslog]      sto:                {DRIVERSTORE IMPORT END: exit(0x00000000)} 16:07:59.600
libwdi:debug [syslog]      sto:           {Core Driver Package Import: exit(0x00000000)} 16:07:59.601
libwdi:debug [syslog]      sto:      {Stage Driver Package: exit(0x00000000)} 16:07:59.602
libwdi:debug [syslog]      sto: {Setup Import Driver Package - exit (0x00000000)} 16:07:59.770
libwdi:debug [syslog]      inf: Driver Store Path: C:\WINDOWS\System32\DriverStore\FileRepository\winusb_generic_device.inf_amd64_21c13ade83f2958f\WinUSB_Generic_Device.inf
libwdi:debug [syslog]      inf: Published Inf Path: C:\WINDOWS\INF\oem42.inf
libwdi:debug [process_message] Switching timeout back to finite
libwdi:debug [installer process] copied inf to C:\WINDOWS\INF\oem42.inf
libwdi:debug [installer process] re-enumerating driver node <root>...
libwdi:debug [installer process] re-enumeration succeeded...
libwdi:debug [process_message] Installer process completed
libwdi:debug [installer process] successfully restored the system restore point creation setting
Driver Installation: SUCCESS
0 devices found.
```

**Comment by maximus-sallam** [comment] 2024-04-15 15:35
Thanks for your reply. I initially attempted to install the WinUSB driver, but that failed, so I attempted to install the WCID driver just to see if it would install. It's not the driver I need though. My apologies for attaching the wrong log.

I'm running Windows 11 Pro arm64 in UTM installed from 22631.2861.231204-0538.23H2_NI_RELEASE_SVC_REFRESH_CLIENTCONSUMER_RET_A64FRE_en-us.iso on a 2023 MacBook Pro M3 Max SoC. My VM has 16 cores and 63G RAM allocated to it. I attempted disabling Windows 11 Code Integrity both through the Security Center and throught the Advanced restart options with no success.

**Comment by pbatard** [comment] 2024-04-15 15:38
Oh, so you are running Windows 11 on ARM64. Damn, I thought you were running on x64 and that we might get a clue on the different ARM64 behaviour.

In this case, I'm afraid your issue is a duplicate of #289 and you may want to try to apply the "workaround" you will find there.

As a result, since this is a duplicate, I will close this issue.

**Closed by pbatard** 2024-04-15 15:38 UTC
